paths:
  testcomplete: "C:/Program Files (x86)/SmartBear/TestComplete 9/Bin/TestComplete.exe"
  shared: "Z:/RhoStudioShare"
  rhostudio_ws: "C:/Users/rhomobile/workspace"
  eclipse: ""
  temp-folder: "c:/TEMP"
  git: "C:/Program Files (x86)/Git"

ui:
  reports: "c:/TEMP"
  
unit: